### ISSUE TITLE
Syntax Error with SQLite

### ISSUE THREAD

**Issue by pitw** [soranoba/pageboy#3]
If using SQLite as Database and trying to paginate with pageboy the following error occur on page 2:

...near "OFFSET": syntax error
 SELECT count(1) FROM `xx` ORDER BY uuid desc OFFSET 10

SQLite needs Limit when using Offset - somehow pageboy drops limit in that case.

**Comment by soranoba** [comment]
Hi, @pitw 

I don't have SQLite environment right now, so I'm not running it, but...
I think it's because the LIMIT clause isn't specified.
The reason is [GORM isn't added to the query when Limit is 0](https://github.com/go-gorm/gorm/blob/dbc6b34dce7f5c4ce6f358d23bc70ac738af7793/clause/limit.go#L17-L29).

First, please make sure the PerPage value is correct. ([PerPage must be greater than 0](https://github.com/soranoba/pageboy/blob/bc2a089591ee5bf4da8e875accdfc0c5da9b5ed9/pager.go#L43-L53))
If the value is incorrect, it will not behave correctly.

**Comment by soranoba** [comment]
The default value should be specified like this.
https://github.com/soranoba/pageboy/blob/bc2a089591ee5bf4da8e875accdfc0c5da9b5ed9/pager_test.go#L146-L149

**Comment by pitw** [comment]
I specified Limit in all possible ways - as soon as you go to Page 2 it doesnt work.

I created a minimal example which reproduces the error here:
https://gist.github.com/pitw/da59505be1a0512403b6a8bc839f9b90

**Comment by soranoba** [comment]
thank you for sample code.
I fix this bug at #4

**Comment by soranoba** [comment]
If you look still have bugs, please report them on this issue or a new issue.
Thanks.
